apiVersion: v1
kind: Secret
metadata:
  name: postgres-env
type: Opaque
stringData:
  POSTGRES_USER: example # postgres config variable, default to postgres
  POSTGRES_PASSWORD: secret # postgres config variable, default to 1234